export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const POST_POST_SUCCESS = 'POST_POST_SUCCESS';
export const PUT_POST_SUCCESS = 'PUT_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POSTS_SUCCESS';

export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const POST_POST_ERROR = 'POST_POST_ERROR';
export const PUT_POST_ERROR = 'PUT_POST_ERROR';
export const DELETE_POST_ERROR = 'DELETE_POSTS_ERROR';

export const PUT_POSTFILE_ERROR = 'PUT_POSTFILE_ERROR';
export const PUT_POSTFILE_SUCCESS = 'PUT_POSTFILE_SUCCESS';

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';

export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';

export const SEND_LIKE_SUCCESS = 'SEND_LIKE_SUCCESS';
export const SEND_LIKE_ERROR = 'SEND_LIKE_ERROR';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const PUT_USER_SUCCESS = 'PUT_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const POST_USER_ERROR = 'POST_USER_ERROR';
export const PUT_USER_ERROR = 'PUT_USER_ERROR';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const SET_LOADING_START = 'SET_LOADING_START';
export const SET_LOADING_END = 'SET_LOADING_END';

export const FILTER_BY_VALUE_USER = 'FILTER_BY_VALUE_USER';
export const FILTER_BY_VALUE_POST = 'FILTER_BY_VALUE_POST';

export const SET_MODAL_CREATE_TRUE = 'SET_MODAL_CREATE_TRUE';
export const SET_MODAL_CREATE_FALSE = 'SET_MODAL_CREATE_FALSE';
export const SET_MODAL_EDIT_TRUE = 'SET_MODAL_EDIT_TRUE';
export const SET_MODAL_EDIT_FALSE = 'SET_MODAL_EDIT_FALSE';
export const SET_MODAL_DELETE_TRUE = 'SET_MODAL_DELETE_TRUE';
export const SET_MODAL_DELETE_FALSE = 'SET_MODAL_DELETE_FALSE';
export const SET_MODAL_EDITFILE_TRUE = 'SET_MODAL_EDITFILE_TRUE';
export const SET_MODAL_EDITFILE_FALSE = 'SET_MODAL_EDITFILE_FALSE';
export const SET_MODAL_MESSAGE_TRUE = 'SET_MODAL_MESSAGE_TRUE';
export const SET_MODAL_MESSAGE_FALSE = 'SET_MODAL_MESSAGE_FALSE';

export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';
export const HTTP_OTHER_ERROR = 'HTTP_OTHER_ERROR';

export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_ERROR = 'GET_FRIENDS_ERROR';

export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_ERROR = 'GET_CHATS_ERROR';
export const POST_CHAT_SUCCESS = 'POST_CHAT_SUCCESS';
export const POST_CHAT_ERROR = 'POST_CHAT_ERROR';

export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const ANSWER_ON_FRIENDSHIP = 'ANSWER_ON_FRIENDSHIP';